#!/usr/bin/python2

import os
import re
import socket
import datetime

as_list = [
	("AS25489", "Aquatix")
]

cidr_file = "/etc/postfix/cidr_spamninja"

def get_as_networks(as_id):
	sock = socket.create_connection(('whois.ripe.net', 43))
	try:
		sock.sendall("-T route -i origin %s\r\n" % as_id)
		for line in sock.makefile().readlines():
			line = line.strip()
			if line.startswith("route:"):
				net = line.split(" ")[-1]
				yield net
	finally:
		sock.close()

cidr = open(cidr_file, "r").read()

if not "### BEGIN SPAMNINJA SECTION" in cidr:
	cidr += "\n### BEGIN SPAMNINJA SECTION\n### END SPAMNINJA SECTION\n"

s = ""
s += "# Autogenerated by SpamNinja on %s\n\n" % datetime.datetime.now().ctime()
for as_id, as_name in as_list:
	print "Querying %s (%s)" % (as_name, as_id)
	s += "# %s (%s)\n" % (as_name, as_id)
	for net in get_as_networks(as_id):
		print "  %s" % net
		s += "%s REJECT Blocked by SpamNinja\n" % net

cidr = re.sub(r"### BEGIN SPAMNINJA SECTION.*### END SPAMNINJA SECTION",
       "### BEGIN SPAMNINJA SECTION\n%s### END SPAMNINJA SECTION" % s,
       cidr, flags=re.DOTALL)

open(cidr_file, "w").write(cidr)

os.system("postfix reload 2>&1")
