#!/usr/bin/python2

import os
import datetime
import requests

spam_mnts = [
	"AQUATIX-MNT",
]

def get_nets_from_mnt(mnt):
	print "Fetching networks for %s from ripe..." % mnt
	params = {
		"inverse-attribute": "mnt-by",
		"type-filter": "route",
		"query-string": mnt
	}
	headers = {
		"Accept": "application/json"
	}
	r = requests.get("http://rest.db.ripe.net/search", params=params, headers=headers)
	nets = []
	for obj in r.json()["objects"]["object"]:
		if obj["type"] != "route":
			continue
		for atr in obj["primary-key"]["attribute"]:
			if atr["name"] == "route":
				print "  %s" % atr["value"]
				nets.append(atr["value"])
	return nets

networks = []
for mnt in spam_mnts:
	networks.extend(get_nets_from_mnt(mnt))

with open("/etc/postfix/cidr_spamninja", "w") as f:
	f.write("# Autogenerated by SpamNinja on %s\n\n" % datetime.datetime.now().ctime())
	for net in networks:
		f.write("%s REJECT Blocked by SpamNinja\n" % net)

os.system("postfix reload 2>&1")
